use master
GO

ALTER DATABASE PTG_GPP_111144 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_103673 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_121061 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_107517 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_109798 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_100394 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_104499 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_101995 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_105411 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_101931 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_109310 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_101076 SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO