use master
GO

ALTER DATABASE PTG_GPP_111144 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_103673 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_121061 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_107517 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_109798 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_100394 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_104499 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_101995 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_105411 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_101931 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_109310 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO
ALTER DATABASE PTG_GPP_101076 SET ONLINE WITH ROLLBACK IMMEDIATE 
GO